[package]
name = "anti_virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
walkdir = "2.3.2"
rayon = "1.5.1"
fnv = "1.0.7"
once_cell = "1.8.0"
crossbeam = "0.8.1"